import React from "react";
import Nav from "../components/nav";
import Footer from "../components/footer";
import Head from "next/head";

function contact() {
  return (
    <>
      <Head>
        <title>Timeless Trinkets | Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="h-screen"></main>
      <Footer />
    </>
  );
}

export default contact;
