import Head from "next/head";
import Nav from "../components/nav";
import Feature from "../components/feature";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Timeless Trinkets | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main
        className="h-screen pt-16 w-100 flex items-center bg-right-bottom bg-cover bg-gray-500 bg-blend-darken lg:bg-blend-normal"
        style={{ backgroundImage: "url('../landing.png')" }}
      >
        <div className="container mx-auto px-3">
          <div className="lg:w-1/2">
            <h2 className="text-5xl lg:text-6xl font-bold text-light1">
              Get Your Hands on Retro Fun!
            </h2>
            <h4 className="mt-5 lg:text-xl font-semibold text-light1 lg:text-light2">
              Play a wide range of classic and modern games on our latest retro
              handheld gaming devices — now available at affordable prices!
            </h4>
            <div className="flex mt-3">
              <a
                href="#"
                className="mr-3 px-10 py-2 text-lg bg-green-500 text-light1 font-semibold rounded-sm hover:bg-green-600 transition"
              >
                Shop Now
              </a>
              <a
                href="#"
                className="px-3 py-2 text-lg text-light1 border rounded-sm hover:bg-light1 hover:text-dark2 transition"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
      </main>
      <section className="bg-light1">
        <div className="container mx-auto px-10 py-24">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10">
            <Feature
              icon={
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  className="w-20 h-20"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
              }
              head="Reasonable Prices"
              body="We offer pocket-friendly prices without compromising on quality. Our products are trusted, tested and good to go!"
            />
            <Feature
              icon={
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  className="w-20 h-20"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"
                  />
                </svg>
              }
              head="Up-to-date"
              body="We always keep our selection updated with the latest retro handheld gaming devices. So, stay ahead of the curve and check out our selection now!"
            />
            <Feature
              icon={
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  className="w-20 h-20"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"
                  />
                </svg>
              }
              head="Premium"
              body="We take pride in our products and only offer the best quality gaming devices that have been thoroughly tested and are guaranteed to give you an enjoyable experience."
            />
            <Feature
              icon={
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  className="w-20 h-20"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
                  />
                </svg>
              }
              head="Easy to use"
              body="Our retro handheld consoles are simple and easy to use, allowing you to get started playing right away with minimal setup required."
            />
          </div>
        </div>
        <div className="container mx-auto px-10 py-16 bg-dark1 rounded">
          <div className="grid lg:grid-cols-2 gap-10">
            <div className="flex justify-center items-center">
              <Image
                className="rounded hover:scale-105 transition"
                src="/arcade.jpg"
                alt="Arcade"
                width={400}
                height={400}
              />
            </div>
            <div className="text-light1">
              <h3 className="text-3xl italic font-bold">
                Remember those times?
              </h3>
              <br />
              <p className="text-lg">
                The arcade was the place to be for many of us growing up in the
                80s and 90s. For a few coins, we could play hours of classic
                games like Pac-Man, Donkey Kong, and Street Fighter. It was a
                time of innocent fun and nostalgia that remains with us today.
              </p>
            </div>
            <div className="flex justify-center items-center">
              <Image
                className="rounded hover:scale-105 transition"
                src="/gameboy.jpg"
                alt="Gameboy"
                width={400}
                height={400}
              />
            </div>
            <div className="text-light1">
              <h3 className="text-3xl italic font-bold">or maybe...</h3>
              <br />
              <p>
                The nostalgia of old handheld game consoles such as the Gameboy
                and PSP is something that you can relate to. These consoles were
                popular for their portability, allowing gamers to take their
                favorite games with them wherever they went. With new
                advancements in technology, these classic handhelds have been
                replaced by more powerful devices, yet there&apos;s still
                something special about revisiting these old games that makes
                them so beloved.
              </p>
            </div>
          </div>
        </div>
        <div
          className="w-screen py-24 my-24 text-light1 flex flex-col items-center justify-center bg-gray-900 bg-blend-overlay bg-center bg-cover bg-fixed"
          style={{ backgroundImage: "url('/collection.jpg')" }}
        >
          <h2 className="text-4xl font-bold text-center">
            You&apos;ve come to the right place.
          </h2>
          <hr className="my-5 text-dark2" />
          <h3 className="text-center text-2xl px-10">
            Timeless Trinkets offers the latest and greatest retro handhelds,
            perfect for any collector or enthusiast. Get your hands on these
            timeless trinkets at an affordable price!
          </h3>
          <Link
            href="/about"
            className="mt-10 px-10 py-2 rounded-full border border-teal-300 text-teal-300 hover:bg-teal-300 hover:text-black transition"
          >
            View Products{" "}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-4 h-4 inline"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
              />
            </svg>
          </Link>
        </div>
      </section>
    </>
  );
}
