import Head from "next/head";
import Nav from "../components/nav";
import Footer from "../components/footer";
import Feature from "../components/feature";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Timeless Trinkets | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main
        className="h-screen pt-16 w-100 flex items-center bg-right-bottom bg-cover bg-gray-800 bg-blend-overlay lg:bg-gray-500"
        style={{ backgroundImage: "url('../landing.png')" }}
      >
        <div className="container mx-auto px-3">
          <div className="lg:w-1/2">
            <h2 className="text-5xl lg:text-6xl font-bold text-light1">
              Get Your Hands on Retro Fun!
            </h2>
            <h4 className="mt-5 lg:text-xl font-semibold text-light1 lg:text-light2">
              Play a wide range of classic and modern games on our latest retro
              handheld gaming devices — now available at affordable prices!
            </h4>
            <div className="flex mt-3">
              <a
                href="/products"
                className="mr-3 px-10 py-2 text-lg bg-green-500 text-light1 font-semibold rounded-sm hover:bg-green-600 transition"
              >
                Shop Now
              </a>
              <a
                href="#features"
                className="px-3 py-2 text-lg text-light1 border rounded-sm hover:bg-light1 hover:text-dark2 transition"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
      </main>
      <section className="bg-light1">
        <div className="container mx-auto px-10 py-24" id="features">
          <h2 className="text-center text-4xl font-bold text-dark2 mb-10">
            Why choose us?
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10">
            <Feature
              icon={<i className="fa-solid fa-coins text-6xl my-5"></i>}
              head="Reasonable Prices"
              body="We offer pocket-friendly prices without compromising on quality. Our products are trusted, tested and good to go!"
            />
            <Feature
              icon={
                <i className="fa-solid fa-calendar-check text-6xl my-5"></i>
              }
              head="Up-to-date"
              body="We always keep our selection updated with the latest retro handheld gaming devices. So, stay ahead of the curve and check out our selection now!"
            />
            <Feature
              icon={<i className="fa-solid fa-shield-halved text-6xl my-5"></i>}
              head="Premium"
              body="We take pride in our products and only offer the best quality gaming devices that have been thoroughly tested and are guaranteed to give you an enjoyable experience."
            />
            <Feature
              icon={<i className="fa-solid fa-heart text-6xl my-5"></i>}
              head="Easy to use"
              body="Our retro handheld consoles are simple and easy to use, allowing you to get started playing right away with minimal setup required."
            />
          </div>
        </div>
        <div className="container mx-auto px-10 py-16 bg-dark1 rounded">
          <div className="grid lg:grid-cols-2 gap-10">
            <div className="flex justify-center items-center">
              <Image
                className="rounded hover:scale-105 transition"
                src="/arcade.jpg"
                alt="Arcade"
                width={400}
                height={400}
              />
            </div>
            <div className="text-light1">
              <h3 className="text-3xl italic font-bold">
                Remember those times?
              </h3>
              <br />
              <p className="text-lg">
                The arcade was the place to be for many of us growing up in the
                80s and 90s. For a few coins, we could play hours of classic
                games like Pac-Man, Donkey Kong, and Street Fighter. It was a
                time of innocent fun and nostalgia that remains with us today.
              </p>
            </div>
            <div className="flex justify-center items-center">
              <Image
                className="rounded hover:scale-105 transition"
                src="/gameboy.jpg"
                alt="Gameboy"
                width={400}
                height={400}
              />
            </div>
            <div className="text-light1">
              <h3 className="text-3xl italic font-bold">or maybe...</h3>
              <br />
              <p>
                The nostalgia of old handheld game consoles such as the Gameboy
                and PSP is something that you can relate to. These consoles were
                popular for their portability, allowing gamers to take their
                favorite games with them wherever they went. With new
                advancements in technology, these classic handhelds have been
                replaced by more powerful devices, yet there&apos;s still
                something special about revisiting these old games that makes
                them so beloved.
              </p>
            </div>
          </div>
        </div>
        <div
          className="w-screen py-24 mt-24 text-light1 flex flex-col items-center justify-center bg-gray-900 bg-blend-overlay bg-center bg-cover bg-fixed"
          style={{ backgroundImage: "url('/collection.jpg')" }}
        >
          <h2 className="text-4xl font-bold text-center">
            You&apos;ve come to the right place.
          </h2>
          <hr className="my-5 text-dark2" />
          <h3 className="text-center text-2xl px-10">
            Timeless Trinkets offers the latest and greatest retro handhelds,
            perfect for any collector or enthusiast. Get your hands on these
            timeless trinkets at an affordable price!
          </h3>
          <Link
            href="/products"
            className="mt-10 px-10 py-2 rounded-full border border-teal-300 text-teal-300 hover:bg-teal-300 hover:text-black transition"
          >
            View Products <i className="fa-solid fa-angles-right"></i>
          </Link>
        </div>
        <div className="container mx-auto py-10 px-5">
          <h4 className="text-2xl">We sell stuff from:</h4>
          <div className="flex justify-center items-center flex-wrap mt-6">
            <div className="relative w-60 h-20 border">
              <Image
                src="/anbernic.png"
                alt="Anbernic"
                className="object-contain"
                fill
              />
            </div>
            <div className="relative w-60 h-20 border">
              <Image
                src="/miyoo.png"
                alt="Miyoo"
                className="object-contain"
                fill
              />
            </div>
            <div className="relative w-60 h-20 border">
              <Image
                src="/retroid.png"
                alt="Retroid"
                className="object-contain"
                fill
              />
            </div>
            <div className="relative w-60 h-20 border">
              <Image
                src="/powkiddy.png"
                alt="Powkiddy"
                className="object-contain"
                fill
              />
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
