import Head from "next/head";
import Nav from "../components/nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Timeless Trinkets | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main
        className="h-screen pt-16 w-100 flex items-center bg-right-bottom bg-cover bg-gray-500 bg-blend-darken lg:bg-blend-normal"
        style={{ backgroundImage: "url('../landing.png')" }}
      >
        <div className="container mx-auto px-3">
          <div className="lg:w-1/2">
            <h2 className="text-5xl lg:text-6xl font-bold text-light1">
              Take your gaming experience to the next level
            </h2>
            <h4 className="mt-5 lg:text-xl font-semibold text-light1 lg:text-light2">
              Play a wide range of classic and modern games on our latest retro
              handheld gaming devices — now available at affordable prices!
            </h4>
            <div className="flex mt-3">
              <a
                href="#"
                className="mr-3 px-10 py-2 text-lg bg-green-500 text-light1 font-semibold rounded-sm hover:bg-green-600 transition"
              >
                Shop Now
              </a>
              <a
                href="#"
                className="px-3 py-2 text-lg bg-dark2 text-light1 border rounded-sm hover:bg-light1 hover:text-dark2 transition"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
